language: ruby
matrix:
  include:
    - rvm: "2.0"
      gemfile: Gemfile-activerecord-4.0.x
    - rvm: "2.0"
      gemfile: Gemfile-activerecord-4.2.x
    - rvm: "2.2"
      gemfile: Gemfile-activerecord-5.0.x
    - rvm: "2.6"
      gemfile: Gemfile-activerecord-5.0.x
    - rvm: "2.2"
      gemfile: Gemfile-activerecord-5.2.x
    - rvm: "2.6"
      gemfile: Gemfile-activerecord-5.2.x
